# Generated by Django 3.2.25 on 2024-12-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0011_cart_purchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
